/// Compiles the code blocks in llms.txt's Testing section.
///
/// llms.txt is the product's contract with agents — README calls it enough to
/// write conforming keta code by hand — and it had no gate of any kind. Two of
/// its testing snippets did not compile: one passed `uri:` to `testContext`,
/// whose parameter is `path`, and one misused `FailureMode.wrap` twice over
/// (wrong callback type, and never calling the closure it returns). Both were
/// introduced by a restructuring pass and read perfectly plausibly. An agent
/// following them writes code that does not build.
///
/// Scope, deliberately: the Testing section only. Its snippets depend on
/// `package:keta` and `package:keta/test.dart` and nothing else, so this test
/// can compile them from inside this package. Sections that reach for
/// keta_db, keta_openapi, or keta_oidc would need a package that depends on
/// all of them, which does not exist and should not be invented for a doc
/// check. This closes the hole where it was actually shown to open.
///
/// Undefined names an excerpt legitimately leaves to the reader (`app`, `env`,
/// a handler) are declared `dynamic` by the harness, so a call on one of them
/// is not what this checks. What it checks is every name that comes from keta
/// itself — a constructor, a named argument, a static, a type — which is
/// exactly the class of error that occurred.
@TestOn('vm')
library;

import 'dart:io';

import 'package:test/test.dart';

/// The fenced `dart` blocks inside the `## Testing` section.
List<String> _testingSnippets(String doc) {
  final lines = doc.split('\n');
  final start = lines.indexWhere((l) => l.trim() == '## Testing');
  if (start < 0) return const [];
  var end = lines.indexWhere((l) => l.startsWith('## '), start + 1);
  if (end < 0) end = lines.length;

  final blocks = <String>[];
  var inBlock = false;
  var current = <String>[];
  for (final line in lines.sublist(start, end)) {
    if (line.trimRight() == '```dart') {
      inBlock = true;
      current = [];
    } else if (inBlock && line.trimRight() == '```') {
      inBlock = false;
      blocks.add(current.join('\n'));
    } else if (inBlock) {
      current.add(line);
    }
  }
  return blocks;
}

/// Wraps [snippet] so it is a compilable library: keta's imports, plus the
/// placeholders an excerpt is entitled to leave undefined.
String _harness(String snippet) =>
    '''
// GENERATED by llms_snippets_test.dart — not part of the package.
// ignore_for_file: unused_local_variable, avoid_print, always_declare_return_types
import 'package:keta/keta.dart';
import 'package:keta/test.dart';
import 'package:test/test.dart';

// Typed where keta's own signatures constrain them, so a snippet that passes
// the wrong thing to TestClient or TestServer is still caught; `dynamic` only
// where the reader is genuinely free to supply anything.
late App<Object?> app;
late Object? env;
dynamic myHandler;
dynamic userDtoSchema;
dynamic badBody;

void snippet() {
$snippet
}
''';

void main() {
  test(
    'every dart block in the Testing section compiles',
    () async {
      // The package root, from the test's own location, so this works from any
      // working directory the runner is launched in.
      final packageRoot = Directory.current.path;
      final doc = File('$packageRoot/../../llms.txt');
      expect(
        doc.existsSync(),
        isTrue,
        reason: 'llms.txt not found from $packageRoot',
      );

      final snippets = _testingSnippets(doc.readAsStringSync());
      expect(
        snippets,
        isNotEmpty,
        reason:
            'the Testing section has no dart blocks — extraction is broken, '
            'which would make this gate silently vacuous',
      );

      // Written inside the package so `package:keta` resolves through its own
      // package config, and under .dart_tool so it is never part of the tree the
      // package's own analyze walks.
      final scratch = Directory('$packageRoot/.dart_tool/llms_check');
      if (scratch.existsSync()) scratch.deleteSync(recursive: true);
      scratch.createSync(recursive: true);
      addTearDown(() => scratch.deleteSync(recursive: true));

      final files = <String>[];
      for (var i = 0; i < snippets.length; i++) {
        final f = File('${scratch.path}/snippet_$i.dart')
          ..writeAsStringSync(_harness(snippets[i]));
        files.add(f.path);
      }

      final result = await Process.run(Platform.resolvedExecutable, [
        'analyze',
        '--no-fatal-warnings',
        ...files,
      ], workingDirectory: packageRoot);

      // Errors only: a snippet is an excerpt, so unused imports and missing
      // return types are noise, but an undefined name or a wrong argument is the
      // doc being wrong.
      final errors = '${result.stdout}'
          .split('\n')
          .where((l) => l.contains('error -'))
          .toList();
      expect(
        errors,
        isEmpty,
        reason:
            'llms.txt Testing snippets do not compile:\n${errors.join('\n')}',
      );
    },
    timeout: const Timeout(Duration(minutes: 2)),
  );
}
